name: 'Upload BOM to Dependency-Track (behind Cloudflare)'
author: Jeremy Chapeau (forked from Patrick Dwyer)
description: 'Uploads a CycloneDX software bill of materials to a Dependency-Track server behing Cloudflare Access'
inputs:
  serverhostname:
    description: 'Dependency-Track hostname'
    required: true
  cfclientid:
    description: 'CF Access Client ID'
    required: true
  cfclientsecret:
    description: 'CF Access Client Secret'
    required: true
  port:
    description: 'Dependency-Track port'
    required: false
    default: 443
  protocol:
    description: 'Dependency-Track protocol'
    required: false
    default: 'https'
  apikey:
    description: 'Dependency-Track API key'
    required: true
  project:
    description: 'Project in Dependency-Track'
    required: false
  projectname:
    description: 'Project name in Dependency-Track'
    required: false
  projectversion:
    description: 'Project version in Dependency-Track'
    required: false
  autocreate:
    description: "Automatically create the project in Dependency-Track if it doesn't exist"
    default: 'false'
    required: false
  bomfilename:
    description: 'Path and filename of the BOM'
    default: 'bom.xml'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
